export interface ServiceDefinition {
  slug: string
  name: string
  short_description: string
  long_description: string
  industries: string[]
  category: ServiceCategory
  pain_points: string[]
  tags: string[]
  price_monthly: string
  price_setup: string | null
  timeline: string
  deliverables: string[]
  roi_estimate: string
  case_study_title: string | null
  case_study_text: string | null
  featured: boolean
  sort_order: number
}

export type ServiceCategory =
  | "ventas"
  | "automatizacion"
  | "atencion"
  | "presencia_digital"
  | "datos_analytics"
  | "fidelizacion"
  | "operaciones"
  | "marketing"

export const SERVICE_CATEGORIES: Record<ServiceCategory, { label: string; description: string }> = {
  ventas: { label: "Ventas & Conversión", description: "Estrategias y herramientas para vender más" },
  automatizacion: { label: "Automatización", description: "Deja que la tecnología haga el trabajo repetitivo" },
  atencion: { label: "Atención al Cliente", description: "Responde más rápido y mejor" },
  presencia_digital: { label: "Presencia Digital", description: "Que te encuentren en internet" },
  datos_analytics: { label: "Datos & Analytics", description: "Decisiones basadas en datos reales" },
  fidelizacion: { label: "Fidelización", description: "Clientes que vuelven una y otra vez" },
  operaciones: { label: "Operaciones", description: "Optimiza tus procesos internos" },
  marketing: { label: "Marketing Digital", description: "Atrae más clientes potenciales" },
}

export const SERVICES_CATALOG: ServiceDefinition[] = [
  // ==========================================
  // RESTAURANTE / FOOD
  // ==========================================
  {
    slug: "restaurante-ai-whatsapp",
    name: "Agente AI para WhatsApp",
    short_description: "Automatizamos la atención al cliente con un agente de IA en WhatsApp que toma pedidos y reservas 24/7.",
    long_description: "Implementamos un asistente virtual impulsado por IA en tu WhatsApp Business que puede tomar pedidos, gestionar reservas, responder preguntas frecuentes (horarios, menú, precios) y escalar a un humano cuando sea necesario. Tus clientes obtienen respuesta inmediata sin importar la hora.",
    industries: ["restaurante"],
    category: "atencion",
    pain_points: ["atencion_cliente", "procesos_manuales", "ventas_estancadas"],
    tags: ["whatsapp", "ia", "chatbot", "pedidos", "reservas"],
    price_monthly: "$350 - $700 USD/mes",
    price_setup: "$500 USD",
    timeline: "1-2 semanas",
    deliverables: [
      "Agente AI entrenado con tu menú y horarios",
      "Integración con WhatsApp Business API",
      "Flujo de pedidos y/o reservas automatizado",
      "Panel de monitoreo de conversaciones",
      "Entrenamiento al equipo",
    ],
    roi_estimate: "Recupera hasta 15 horas/semana en atención y captura pedidos fuera del horario laboral",
    case_study_title: null,
    case_study_text: null,
    featured: true,
    sort_order: 1,
  },
  {
    slug: "restaurante-menu-digital-qr",
    name: "Menú Digital QR + Pedidos",
    short_description: "Tu menú interactivo con código QR para que los clientes pidan desde su mesa sin esperar.",
    long_description: "Creamos un menú digital responsivo al que tus clientes acceden escaneando un código QR en la mesa. Pueden ver fotos, descripciones, precios y hacer su pedido directamente desde el celular. El pedido llega a tu cocina en tiempo real.",
    industries: ["restaurante"],
    category: "ventas",
    pain_points: ["procesos_manuales", "atencion_cliente", "sin_trazabilidad"],
    tags: ["qr", "menu", "pedidos", "digital"],
    price_monthly: "$200 - $400 USD/mes",
    price_setup: "$300 USD",
    timeline: "1 semana",
    deliverables: [
      "Menú digital responsivo con fotos y precios",
      "Códigos QR para cada mesa",
      "Sistema de pedidos integrado",
      "Notificaciones en tiempo real a cocina",
      "Panel de control de pedidos",
    ],
    roi_estimate: "Aumenta ticket promedio en un 20% con fotos sugerentes y pedidos sin errores",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 2,
  },
  {
    slug: "restaurante-pedidos-online",
    name: "Sistema de Pedidos Online (Sin Comisiones)",
    short_description: "Tu propia plataforma de delivery sin pagar comisiones a UberEats o Didi.",
    long_description: "Desarrollamos tu plataforma de pedidos online blanca (white label) para que recibas pedidos directos sin pagar comisiones del 30% a las plataformas de delivery. Integramos pagos en línea, notificaciones al cliente y gestión de reparto.",
    industries: ["restaurante"],
    category: "ventas",
    pain_points: ["ventas_estancadas", "presencia_online", "sin_trazabilidad"],
    tags: ["delivery", "ecommerce", "pedidos", "sin-comisiones"],
    price_monthly: "$500 - $1,000 USD/mes",
    price_setup: "$1,200 USD",
    timeline: "3-4 semanas",
    deliverables: [
      "Plataforma web white label con dominio propio",
      "Catálogo de productos sincronizado",
      "Pagos en línea (tarjeta, transferencia, efectivo)",
      "Notificaciones automáticas al cliente",
      "Panel de administración de pedidos",
    ],
    roi_estimate: "Ahorra hasta 30% por pedido vs plataformas tradicionales de delivery",
    case_study_title: null,
    case_study_text: null,
    featured: true,
    sort_order: 3,
  },
  {
    slug: "restaurante-fidelizacion",
    name: "Programa de Lealtad Digital",
    short_description: "Crea un programa de puntos y recompensas digital que haga que tus clientes vuelvan siempre.",
    long_description: "Implementamos un programa de lealtad digital con tarjeta de puntos virtual. Tus clientes acumulan puntos con cada visita o pedido y los canjean por descuentos o productos. Todo desde su celular, sin tarjetas físicas.",
    industries: ["restaurante"],
    category: "fidelizacion",
    pain_points: ["ventas_estancadas", "falta_visibilidad", "atencion_cliente"],
    tags: ["lealtad", "puntos", "fidelizacion", "recompensas"],
    price_monthly: "$250 - $500 USD/mes",
    price_setup: "$400 USD",
    timeline: "2 semanas",
    deliverables: [
      "Sistema de puntos digital (web + WhatsApp)",
      "Registro de clientes con historial de visitas",
      "Campañas automáticas de cumpleaños y aniversario",
      "Panel de métricas de retención",
      "Notificaciones push de ofertas exclusivas",
    ],
    roi_estimate: "Aumenta frecuencia de visita en un 35% con clientes registrados en el programa",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 4,
  },
  {
    slug: "restaurante-automatizacion-resenas",
    name: "Gestión Automática de Reseñas",
    short_description: "Pedimos reseñas a tus clientes satisfechos automáticamente para mejorar tu reputación online.",
    long_description: "Configuramos un sistema que envía automáticamente un mensaje después de cada visita o pedido pidiendo una reseña en Google o Facebook. Respondemos reseñas por ti con IA y te alertamos de reseñas negativas para que actúes rápido.",
    industries: ["restaurante"],
    category: "marketing",
    pain_points: ["presencia_online", "reputacion"],
    tags: ["resenas", "google", "reputacion", "automatizacion"],
    price_monthly: "$150 - $300 USD/mes",
    price_setup: "$200 USD",
    timeline: "1 semana",
    deliverables: [
      "Automatización de solicitud de reseñas post-venta",
      "Respuesta automática a reseñas positivas",
      "Alertas de reseñas negativas",
      "Dashboard de reputación online",
      "Reporte mensual de métricas de reseñas",
    ],
    roi_estimate: "Cada estrella extra en Google aumenta las visitas en un 9%",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 5,
  },

  // ==========================================
  // RETAIL / ECOMMERCE
  // ==========================================
  {
    slug: "ecommerce-tiktok-shop",
    name: "Conexión con TikTok Shop",
    short_description: "Conectamos tu tienda con TikTok Shop para que vendas directamente desde tus videos.",
    long_description: "Integramos tu catálogo de productos con TikTok Shop para que puedas vender directamente desde tus videos en vivo, videos orgánicos y anuncios. Sincronizamos inventario, precios y pedidos automáticamente.",
    industries: ["retail"],
    category: "ventas",
    pain_points: ["ventas_estancadas", "presencia_online"],
    tags: ["tiktok", "social-selling", "ecommerce", "shop"],
    price_monthly: "$400 - $800 USD/mes",
    price_setup: "$600 USD",
    timeline: "2-3 semanas",
    deliverables: [
      "Integración de catálogo con TikTok Shop",
      "Sincronización automática de inventario",
      "Configuración de métodos de pago y envío",
      "Plantillas de videos persuasivos",
      "Dashboard de ventas TikTok",
    ],
    roi_estimate: "Incremento estimado de 25-40% en ventas a través del canal social",
    case_study_title: null,
    case_study_text: null,
    featured: true,
    sort_order: 1,
  },
  {
    slug: "ecommerce-carritos-abandonados",
    name: "Recuperación de Carritos Abandonados",
    short_description: "Recuperamos ventas perdidas automatizando el seguimiento de clientes que abandonaron su compra.",
    long_description: "Configuramos un sistema que detecta automáticamente cuando un cliente agrega productos al carrito pero no completa la compra. Enviamos mensajes personalizados por WhatsApp y email recordándole su carrito, con incentivos para que regrese.",
    industries: ["retail"],
    category: "ventas",
    pain_points: ["ventas_estancadas", "falta_visibilidad"],
    tags: ["carritos", "abandonados", "recuperacion", "whatsapp", "email"],
    price_monthly: "$300 - $600 USD/mes",
    price_setup: "$350 USD",
    timeline: "1-2 semanas",
    deliverables: [
      "Detección automática de carritos abandonados",
      "Secuencia de 3 mensajes vía WhatsApp + email",
      "Cupones de descuento personalizados",
      "Dashboard de recuperación (tasa de conversión)",
    ],
    roi_estimate: "Recupera 15-30% de las ventas que se pierden en el carrito",
    case_study_title: null,
    case_study_text: null,
    featured: true,
    sort_order: 2,
  },
  {
    slug: "ecommerce-chatbot-ventas",
    name: "Chatbot de Ventas con IA",
    short_description: "Un asistente AI en tu tienda online que recomienda productos y cierra ventas 24/7.",
    long_description: "Implementamos un chatbot con inteligencia artificial en tu ecommerce que ayuda a los clientes a encontrar productos, responde dudas de tallas/precios/envíos y los guía hasta la compra. Se integra con WhatsApp, web y redes sociales.",
    industries: ["retail"],
    category: "atencion",
    pain_points: ["atencion_cliente", "ventas_estancadas", "procesos_manuales"],
    tags: ["chatbot", "ia", "ventas", "ecommerce"],
    price_monthly: "$400 - $800 USD/mes",
    price_setup: "$800 USD",
    timeline: "2-3 semanas",
    deliverables: [
      "Chatbot con IA entrenado con tu catálogo",
      "Integración web, WhatsApp y Messenger",
      "Recomendaciones inteligentes de productos",
      "Captura de leads para seguimiento humano",
      "Analytics de conversaciones y ventas",
    ],
    roi_estimate: "Aumenta tasa de conversión en 20% guiando al cliente hasta la compra",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 3,
  },
  {
    slug: "ecommerce-sincronizacion-inventario",
    name: "Sincronización de Inventario Multicanal",
    short_description: "Mantén tu inventario sincronizado en tiempo real entre tu tienda física, web, marketplaces y redes.",
    long_description: "Implementamos un sistema central que sincroniza tu inventario en todos tus canales de venta (tienda física, Shopify/WooCommerce, Amazon, MercadoLibre, TikTok Shop) en tiempo real. Nunca más vendas algo que no tienes.",
    industries: ["retail"],
    category: "operaciones",
    pain_points: ["sin_trazabilidad", "procesos_manuales", "falta_visibilidad"],
    tags: ["inventario", "sincronizacion", "multicanal", "operaciones"],
    price_monthly: "$500 - $1,000 USD/mes",
    price_setup: "$1,000 USD",
    timeline: "3-4 semanas",
    deliverables: [
      "Conexión con todos tus canales de venta",
      "Sincronización en tiempo real de stock",
      "Alertas de inventario bajo",
      "Reportes de ventas por canal",
      "Dashboard centralizado de inventario",
    ],
    roi_estimate: "Elimina pérdidas por sobreventa y reduce tiempos de conciliación en un 80%",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 4,
  },
  {
    slug: "ecommerce-pagina-ventas-alta-conversion",
    name: "Página de Ventas de Alto Impacto",
    short_description: "Creamos landing pages optimizadas para convertir visitantes en clientes de tu producto estrella.",
    long_description: "Diseñamos y desarrollamos páginas de venta enfocadas en conversión para tu producto o servicio principal. Con copy persuasivo, pruebas sociales, escasez y garantías. Optimizadas para móvil con tiempos de carga ultrarrápidos.",
    industries: ["retail"],
    category: "ventas",
    pain_points: ["ventas_estancadas", "presencia_online"],
    tags: ["landing", "conversion", "pagina-ventas", "copy"],
    price_monthly: "$300 - $600 USD/mes",
    price_setup: "$1,500 USD",
    timeline: "2-3 semanas",
    deliverables: [
      "Landing page con diseño persuasivo",
      "Copywriting profesional",
      "Integración con pasarela de pago",
      "Pixel de seguimiento (Meta, Google)",
      "Pruebas A/B básicas incluidas",
    ],
    roi_estimate: "Landing pages optimizadas convierten 2-3x más que un sitio web genérico",
    case_study_title: null,
    case_study_text: null,
    featured: true,
    sort_order: 5,
  },

  // ==========================================
  // SERVICIOS PROFESIONALES
  // ==========================================
  {
    slug: "servicios-crm-automatizado",
    name: "CRM con Seguimiento Automático",
    short_description: "Implementamos un CRM que registra cada interacción y automatiza el seguimiento de tus leads.",
    long_description: "Configuramos un CRM profesional adaptado a tu negocio de servicios. Registra cada llamada, correo y mensaje automáticamente. Automatizamos recordatorios de seguimiento, cotizaciones y postventa para que nunca se te escape un cliente.",
    industries: ["servicios_profesionales", "inmobiliaria", "tecnologia"],
    category: "operaciones",
    pain_points: ["sin_trazabilidad", "procesos_manuales", "falta_visibilidad"],
    tags: ["crm", "seguimiento", "automatizacion", "leads"],
    price_monthly: "$400 - $800 USD/mes",
    price_setup: "$600 USD",
    timeline: "2-3 semanas",
    deliverables: [
      "CRM configurado con tus procesos",
      "Captura automática de leads desde web y WhatsApp",
      "Secuencias de seguimiento automatizadas",
      "Pipeline visual de ventas",
      "Dashboard de métricas comerciales",
    ],
    roi_estimate: "Aumenta tasa de cierre en 30% con seguimiento oportuno y organizado",
    case_study_title: null,
    case_study_text: null,
    featured: true,
    sort_order: 1,
  },
  {
    slug: "servicios-agenda-digital",
    name: "Agenda Digital con Recordatorios",
    short_description: "Sistema de agendamiento online donde tus clientes reservan y reciben recordatorios automáticos.",
    long_description: "Implementamos una plataforma de agendamiento digital donde tus clientes ven tu disponibilidad en tiempo real y reservan citas. El sistema envía recordatorios por WhatsApp y email, reduce las cancelaciones de última hora y organiza tu calendario automáticamente.",
    industries: ["servicios_profesionales", "salud", "educacion", "inmobiliaria"],
    category: "operaciones",
    pain_points: ["procesos_manuales", "atencion_cliente"],
    tags: ["agenda", "citas", "recordatorios", "calendario"],
    price_monthly: "$200 - $400 USD/mes",
    price_setup: "$300 USD",
    timeline: "1 semana",
    deliverables: [
      "Página de reservas con tu marca",
      "Sincronización con Google Calendar",
      "Recordatorios automáticos (WhatsApp + email)",
      "Confirmación y cancelación self-service",
      "Dashboard de citas y no-shows",
    ],
    roi_estimate: "Reduce no-shows en un 60% y ahorra 10+ horas/semana en coordinación de agendas",
    case_study_title: null,
    case_study_text: null,
    featured: true,
    sort_order: 2,
  },
  {
    slug: "servicios-dashboard-kpis",
    name: "Dashboard de Métricas en Tiempo Real",
    short_description: "Un panel con tus KPIs clave actualizados al instante para tomar mejores decisiones.",
    long_description: "Creamos un dashboard ejecutivo con las métricas que realmente importan para tu negocio: ventas, leads, rentabilidad, productividad. Todo actualizado en tiempo real, accesible desde cualquier dispositivo. Olvídate de los reportes manuales en Excel.",
    industries: ["servicios_profesionales", "retail", "restaurante", "tecnologia", "manufactura", "logistica"],
    category: "datos_analytics",
    pain_points: ["falta_visibilidad", "procesos_manuales"],
    tags: ["dashboard", "kpis", "analytics", "tiempo-real"],
    price_monthly: "$300 - $700 USD/mes",
    price_setup: "$1,000 USD",
    timeline: "2-4 semanas",
    deliverables: [
      "Dashboard ejecutivo con tus KPIs clave",
      "Fuentes de datos conectadas",
      "Actualización automática en tiempo real",
      "Acceso desde web y móvil",
      "Exportación de reportes",
    ],
    roi_estimate: "Toma decisiones 5x más rápido con datos en tiempo real, no reportes del mes pasado",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 3,
  },
  {
    slug: "servicios-email-marketing",
    name: "Email Marketing con Segmentación Inteligente",
    short_description: "Campañas de email automatizadas que nutren leads y convierten clientes sin que muevas un dedo.",
    long_description: "Configuramos un sistema de email marketing con flujos automatizados: bienvenida, seguimiento, recuperación de leads fríos, ofertas personalizadas. Segmentamos tu audiencia por comportamiento para que cada cliente reciba el mensaje correcto en el momento correcto.",
    industries: ["servicios_profesionales", "retail", "educacion", "inmobiliaria", "tecnologia"],
    category: "marketing",
    pain_points: ["ventas_estancadas", "presencia_online"],
    tags: ["email", "marketing", "automatizacion", "newsletter"],
    price_monthly: "$250 - $500 USD/mes",
    price_setup: "$400 USD",
    timeline: "1-2 semanas",
    deliverables: [
      "Configuración de plataforma de email",
      "5 flujos automatizados (bienvenida, follow-up, etc.)",
      "Segmentación de contactos por comportamiento",
      "Plantillas profesionales personalizadas",
      "Reporte mensual de métricas",
    ],
    roi_estimate: "Email marketing genera $42 por cada $1 gastado en promedio",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 4,
  },
  {
    slug: "servicios-cotizaciones-digitales",
    name: "Sistema de Cotizaciones Profesionales",
    short_description: "Cotizaciones digitales profesionales que envías en segundos y rastreas su estado en tiempo real.",
    long_description: "Implementamos un sistema donde generas cotizaciones profesionales con tu marca, las envías por WhatsApp o email, y rastreas si el cliente las abrió, cuánto tiempo las vio y si necesita recordatorio. Olvídate de los PDFs que se pierden.",
    industries: ["servicios_profesionales", "manufactura", "logistica", "tecnologia"],
    category: "ventas",
    pain_points: ["procesos_manuales", "sin_trazabilidad", "ventas_estancadas"],
    tags: ["cotizaciones", "propuestas", "digital", "seguimiento"],
    price_monthly: "$200 - $400 USD/mes",
    price_setup: "$300 USD",
    timeline: "1-2 semanas",
    deliverables: [
      "Sistema de cotizaciones con tu marca",
      "Plantillas personalizables por servicio",
      "Notificaciones cuando el cliente abre la cotización",
      "Recordatorios automáticos de seguimiento",
      "Dashboard de propuestas ganadas/perdidas",
    ],
    roi_estimate: "Cierra 25% más cotizaciones con seguimiento oportuno basado en datos",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 5,
  },

  // ==========================================
  // SALUD
  // ==========================================
  {
    slug: "salud-agenda-citas",
    name: "Agenda de Citas Online",
    short_description: "Tus pacientes agendan citas online 24/7 con recordatorios automáticos que reducen inasistencias.",
    long_description: "Plataforma de agendamiento para consultorios y clínicas donde los pacientes ven horarios disponibles, reservan y reciben recordatorios automáticos. Integración con historial clínico y teleconsulta.",
    industries: ["salud"],
    category: "operaciones",
    pain_points: ["procesos_manuales", "atencion_cliente"],
    tags: ["agenda", "citas", "recordatorios", "pacientes"],
    price_monthly: "$200 - $500 USD/mes",
    price_setup: "$400 USD",
    timeline: "1-2 semanas",
    deliverables: [
      "Portal de agendamiento para pacientes",
      "Recordatorios por WhatsApp y email",
      "Sincronización con calendario del médico",
      "Confirmación y reagendamiento self-service",
      "Dashboard de ocupación y no-shows",
    ],
    roi_estimate: "Reduce inasistencias en un 50% y recupera 8+ horas/semana administrativas",
    case_study_title: null,
    case_study_text: null,
    featured: true,
    sort_order: 1,
  },
  {
    slug: "salud-expediente-digital",
    name: "Historia Clínica Digital",
    short_description: "Digitalizamos el expediente de tus pacientes para que lo tengas siempre a mano y seguro.",
    long_description: "Implementamos un sistema de historia clínica electrónica donde registras consultas, diagnósticos, recetas y estudios. Acceso seguro desde cualquier dispositivo, respaldo en la nube y cumplimiento de protección de datos.",
    industries: ["salud"],
    category: "operaciones",
    pain_points: ["procesos_manuales", "sin_trazabilidad", "falta_visibilidad"],
    tags: ["expediente", "digital", "historia-clinica", "pacientes"],
    price_monthly: "$300 - $600 USD/mes",
    price_setup: "$800 USD",
    timeline: "3-4 semanas",
    deliverables: [
      "Sistema de historia clínica electrónica",
      "Registro de consultas y diagnósticos",
      "Recetas digitales",
      "Historial de estudios y resultados",
      "Respaldo encriptado en la nube",
    ],
    roi_estimate: "Ahorra 12+ horas/semana en gestión de expedientes y mejora la calidad de atención",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 2,
  },
  {
    slug: "salud-chatbot-primer-contacto",
    name: "Chatbot de Primer Contacto",
    short_description: "Un asistente AI que califica y agenda pacientes nuevos automáticamente por WhatsApp.",
    long_description: "Implementamos un chatbot en WhatsApp que recibe pacientes nuevos, recopila síntomas y motivo de consulta, resuelve dudas frecuentes y agenda la cita inicial. Filtra urgencias reales y deriva a especialista cuando es necesario.",
    industries: ["salud"],
    category: "atencion",
    pain_points: ["atencion_cliente", "procesos_manuales", "ventas_estancadas"],
    tags: ["chatbot", "whatsapp", "pacientes", "triage"],
    price_monthly: "$300 - $600 USD/mes",
    price_setup: "$500 USD",
    timeline: "2 semanas",
    deliverables: [
      "Chatbot entrenado en triage médico básico",
      "Integración con WhatsApp Business",
      "Flujo de captación de pacientes nuevos",
      "Conexión con agenda de citas",
      "Reporte de leads y conversiones",
    ],
    roi_estimate: "Capta 40% más pacientes nuevos sin aumentar personal administrativo",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 3,
  },
  {
    slug: "salud-marketing-automatizado",
    name: "Marketing Automatizado para Pacientes",
    short_description: "Campañas automáticas de cumpleaños, citas anuales y promociones para tus pacientes.",
    long_description: "Configuramos flujos de marketing automatizados: recordatorios de chequeos anuales, campañas de cumpleaños, promociones de temporada y reactivación de pacientes inactivos. Todo segmentado por tipo de paciente y tratamiento.",
    industries: ["salud"],
    category: "marketing",
    pain_points: ["ventas_estancadas", "presencia_online", "falta_visibilidad"],
    tags: ["marketing", "automatizacion", "pacientes", "retencion"],
    price_monthly: "$200 - $400 USD/mes",
    price_setup: "$300 USD",
    timeline: "1-2 semanas",
    deliverables: [
      "Flujos automatizados de comunicación",
      "Segmentación por tipo de paciente",
      "Campañas de cumpleaños y recall anual",
      "Reactivación de pacientes inactivos",
      "Reporte mensual de retención",
    ],
    roi_estimate: "Aumenta retención de pacientes en 25% con comunicación constante y personalizada",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 4,
  },

  // ==========================================
  // EDUCACIÓN
  // ==========================================
  {
    slug: "educacion-plataforma-cursos",
    name: "Plataforma de Cursos Online",
    short_description: "Tu propia escuela online con cursos, evaluaciones y certificaciones automatizadas.",
    long_description: "Creamos tu plataforma educativa blanca con gestión de cursos, lecciones en video, evaluaciones, certificados automáticos y pasarela de pagos. Tus alumnos acceden desde cualquier dispositivo y avanzan a su ritmo.",
    industries: ["educacion"],
    category: "ventas",
    pain_points: ["presencia_online", "ventas_estancadas"],
    tags: ["cursos", "online", "plataforma", "e-learning"],
    price_monthly: "$500 - $1,200 USD/mes",
    price_setup: "$2,000 USD",
    timeline: "4-6 semanas",
    deliverables: [
      "Plataforma LMS con tu marca",
      "Gestión de cursos, lecciones y evaluaciones",
      "Certificados digitales automáticos",
      "Pasarela de pagos integrada",
      "Dashboard de estudiantes y progreso",
    ],
    roi_estimate: "Escala tus ingresos sin límite geográfico — un curso online llega a miles de alumnos",
    case_study_title: null,
    case_study_text: null,
    featured: true,
    sort_order: 1,
  },
  {
    slug: "educacion-automatizacion-inscripciones",
    name: "Automatización de Inscripciones",
    short_description: "Proceso de registro automatizado desde el lead hasta la inscripción pagada sin intervención manual.",
    long_description: "Implementamos un flujo completo de inscripción digital: el prospecto llena un formulario, recibe información automática, agenda una llamada de admisión si aplica, y completa el pago en línea. Todo automatizado, sin procesos manuales.",
    industries: ["educacion"],
    category: "operaciones",
    pain_points: ["procesos_manuales", "ventas_estancadas", "sin_trazabilidad"],
    tags: ["inscripciones", "automatizacion", "admissions", "crm"],
    price_monthly: "$300 - $600 USD/mes",
    price_setup: "$500 USD",
    timeline: "2-3 semanas",
    deliverables: [
      "Formulario de registro inteligente",
      "Email y WhatsApp de bienvenida automatizados",
      "Flujo de admisión con recordatorios",
      "Pago en línea integrado",
      "Dashboard de conversión de leads a inscritos",
    ],
    roi_estimate: "Reduce el ciclo de inscripción de días a minutos y aumenta conversión en 35%",
    case_study_title: null,
    case_study_text: null,
    featured: true,
    sort_order: 2,
  },
  {
    slug: "educacion-crm-alumnos",
    name: "CRM de Alumnos",
    short_description: "Gestión completa del ciclo de vida del alumno desde el lead hasta el egresado.",
    long_description: "CRM especializado para instituciones educativas con seguimiento de leads, control de inscripciones, historial académico, comunicación con padres de familia y automatización de cobros recurrentes.",
    industries: ["educacion"],
    category: "operaciones",
    pain_points: ["sin_trazabilidad", "falta_visibilidad", "procesos_manuales"],
    tags: ["crm", "alumnos", "seguimiento", "educacion"],
    price_monthly: "$350 - $700 USD/mes",
    price_setup: "$600 USD",
    timeline: "2-3 semanas",
    deliverables: [
      "CRM con perfiles de alumnos",
      "Seguimiento de leads y conversiones",
      "Control de pagos y cobros recurrentes",
      "Comunicación con padres automatizada",
      "Reportes de retención y desempeño",
    ],
    roi_estimate: "Mejora retención en 20% con comunicación constante y detección temprana de abandono",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 3,
  },

  // ==========================================
  // CROSS-INDUSTRY (aplican a múltiples)
  // ==========================================
  {
    slug: "cross-whatsapp-business-api",
    name: "WhatsApp Business API Profesional",
    short_description: "WhatsApp empresarial con múltiples agentes, plantillas, catálogo y chatbot.",
    long_description: "Implementamos WhatsApp Business API con todas las funcionalidades: varios agentes atendiendo desde la misma línea, plantillas de mensajes aprobadas, catálogo de productos, respuestas rápidas y chatbot para atender 24/7.",
    industries: ["restaurante", "retail", "servicios_profesionales", "salud", "educacion", "inmobiliaria", "tecnologia", "manufactura", "logistica", "otra"],
    category: "atencion",
    pain_points: ["atencion_cliente", "procesos_manuales", "comunicacion_fragmentada"],
    tags: ["whatsapp", "business", "api", "chatbot", "multiagente"],
    price_monthly: "$250 - $600 USD/mes",
    price_setup: "$400 USD",
    timeline: "1-2 semanas",
    deliverables: [
      "Cuenta WhatsApp Business API",
      "Hasta 5 agentes simultáneos",
      "Plantillas de mensajes personalizadas",
      "Catálogo digital de productos/servicios",
      "Chatbot básico para fuera de horario",
    ],
    roi_estimate: "Centraliza toda la comunicación de clientes en un solo lugar y responde 3x más rápido",
    case_study_title: null,
    case_study_text: null,
    featured: true,
    sort_order: 1,
  },
  {
    slug: "cross-automatizacion-procesos",
    name: "Automatización de Procesos Internos",
    short_description: "Identificamos y automatizamos tus procesos manuales para que tu equipo se enfoque en lo importante.",
    long_description: "Auditamos tus procesos operativos, identificamos cuellos de botella y tareas repetitivas, e implementamos automatizaciones con herramientas no-code. Desde facturación automática hasta reportes generados sin intervención humana.",
    industries: ["restaurante", "retail", "servicios_profesionales", "manufactura", "logistica", "tecnologia", "otra"],
    category: "automatizacion",
    pain_points: ["procesos_manuales", "sin_trazabilidad"],
    tags: ["automatizacion", "procesos", "no-code", "eficiencia"],
    price_monthly: "$400 - $1,000 USD/mes",
    price_setup: "$1,500 USD",
    timeline: "3-6 semanas",
    deliverables: [
      "Auditoría de procesos con diagnóstico",
      "Mapeo de automatizaciones priorizadas",
      "Implementación de automatizaciones",
      "Documentación y entrenamiento",
      "Soporte y ajustes por 30 días",
    ],
    roi_estimate: "Recupera 20-40 horas/semana en tareas manuales eliminadas",
    case_study_title: null,
    case_study_text: null,
    featured: true,
    sort_order: 2,
  },
  {
    slug: "cross-generacion-leads",
    name: "Generación de Leads Automatizada",
    short_description: "Atrae clientes potenciales calificados 24/7 con imanes digitales y seguimiento automático.",
    long_description: "Diseñamos e implementamos una máquina de generación de leads: landing pages con imanes digitales (guías, checklists, calculadoras), anuncios segmentados y seguimiento automático por WhatsApp/email hasta la calificación.",
    industries: ["restaurante", "retail", "servicios_profesionales", "salud", "educacion", "inmobiliaria", "tecnologia", "otra"],
    category: "marketing",
    pain_points: ["ventas_estancadas", "presencia_online"],
    tags: ["leads", "generacion", "marketing", "anuncios"],
    price_monthly: "$500 - $1,200 USD/mes",
    price_setup: "$800 USD",
    timeline: "2-3 semanas",
    deliverables: [
      "Landing pages de captación optimizadas",
      "Imanes digitales (guías, templates, calculadoras)",
      "Flujo de seguimiento automatizado",
      "Segmentación de anuncios (Meta/Google)",
      "Dashboard de leads y costo por lead",
    ],
    roi_estimate: "Reduce costo por lead en un 40% con segmentación precisa y seguimiento automatizado",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 3,
  },
  {
    slug: "cross-google-ads-local",
    name: "Campañas de Google Ads Local",
    short_description: "Aparece en las búsquedas de Google cuando tus clientes te buscan en tu zona.",
    long_description: "Configuramos y gestionamos campañas de Google Ads enfocadas en clientes locales. Apareces en búsquedas como 'restaurante cerca de mí' o 'abogado en [ciudad]'. Optimizamos pujas, palabras clave y extensiones de anuncio para maximizar leads.",
    industries: ["restaurante", "retail", "servicios_profesionales", "salud", "inmobiliaria"],
    category: "marketing",
    pain_points: ["presencia_online", "ventas_estancadas"],
    tags: ["google-ads", "ads", "local", "anuncios", "seo"],
    price_monthly: "$400 - $1,000 USD/mes (incluye inversión en anuncios)",
    price_setup: "$300 USD",
    timeline: "1 semana",
    deliverables: [
      "Configuración de campañas Google Ads locales",
      "Investigación de palabras clave locales",
      "Extensiones de ubicación y llamada",
      "Optimización continua de pujas",
      "Reporte semanal de resultados",
    ],
    roi_estimate: "Aparece en el top 3 de búsquedas locales y multiplica tus leads calificados",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 4,
  },
  {
    slug: "cross-estrategia-redes-sociales",
    name: "Estrategia de Redes Sociales",
    short_description: "Contenido y gestión de redes sociales que atrae clientes y construye tu marca.",
    long_description: "Diseñamos una estrategia de contenido para tus redes sociales (Instagram, Facebook, TikTok, LinkedIn) con calendario editorial, creación de contenido visual, copywriting y gestión de comunidad. Medimos resultados y ajustamos constantemente.",
    industries: ["restaurante", "retail", "servicios_profesionales", "salud", "educacion", "inmobiliaria", "tecnologia", "otra"],
    category: "presencia_digital",
    pain_points: ["presencia_online", "ventas_estancadas"],
    tags: ["redes", "contenido", "social-media", "marketing"],
    price_monthly: "$500 - $1,000 USD/mes",
    price_setup: "$400 USD",
    timeline: "2 semanas (continua)",
    deliverables: [
      "Estrategia de contenido personalizada",
      "12 publicaciones/mes por red social",
      "Diseño visual de cada publicación",
      "Respuesta a comentarios y mensajes",
      "Reporte mensual de métricas",
    ],
    roi_estimate: "Construye una comunidad que te recomienda y compra, no solo likes",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 5,
  },
  {
    slug: "cross-pos-digital",
    name: "Punto de Venta Digital",
    short_description: "Sistema de cobro digital con control de inventario, clientes y ventas en tiempo real.",
    long_description: "Implementamos un sistema de punto de venta (POS) digital que registra cada venta, controla inventario, genera tickets y facturas, y te da visibilidad en tiempo real de tu negocio. Ideal para retail, restaurantes y servicios.",
    industries: ["restaurante", "retail", "servicios_profesionales", "salud"],
    category: "operaciones",
    pain_points: ["procesos_manuales", "sin_trazabilidad", "falta_visibilidad"],
    tags: ["pos", "punto-venta", "inventario", "cobro"],
    price_monthly: "$200 - $500 USD/mes",
    price_setup: "$600 USD",
    timeline: "2 semanas",
    deliverables: [
      "Sistema POS en web y móvil",
      "Control de inventario en tiempo real",
      "Generación de tickets y facturas",
      "Historial de clientes y ventas",
      "Reportes automáticos diarios/semanales",
    ],
    roi_estimate: "Elimina errores de caja y reduce mermas de inventario en un 15%",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 6,
  },
  {
    slug: "cross-google-business",
    name: "Optimización de Google Business Profile",
    short_description: "Tu perfil de Google optimizado al máximo para aparecer en búsquedas locales y maps.",
    long_description: "Auditamos y optimizamos tu perfil de Google Business: fotos profesionales, categorías correctas, publicaciones semanales, respuestas a reseñas, atributos y preguntas frecuentes. Aparece en el Google Maps y búsqueda local de tus clientes.",
    industries: ["restaurante", "retail", "servicios_profesionales", "salud", "educacion", "inmobiliaria"],
    category: "presencia_digital",
    pain_points: ["presencia_online"],
    tags: ["google-business", "seo-local", "maps", "optimizacion"],
    price_monthly: "$150 - $300 USD/mes",
    price_setup: "$200 USD",
    timeline: "1 semana",
    deliverables: [
      "Auditoría completa del perfil actual",
      "Optimización de categorías y atributos",
      "Fotos profesionales (si aplica)",
      "Publicaciones semanales",
      "Respuesta a reseñas",
    ],
    roi_estimate: "El 76% de las personas que buscan un negocio local visitan ese mismo día",
    case_study_title: null,
    case_study_text: null,
    featured: false,
    sort_order: 7,
  },
]

export function getServicesByIndustry(industry: string): ServiceDefinition[] {
  return SERVICES_CATALOG.filter((s) => s.industries.includes(industry))
}

export function getServiceBySlug(slug: string): ServiceDefinition | undefined {
  return SERVICES_CATALOG.find((s) => s.slug === slug)
}

export function getServicesByPainPoint(painPoint: string): ServiceDefinition[] {
  return SERVICES_CATALOG.filter((s) => s.pain_points.includes(painPoint))
}

export function getFeaturedServices(): ServiceDefinition[] {
  return SERVICES_CATALOG.filter((s) => s.featured)
}

export function getServicesByCategory(category: ServiceCategory): ServiceDefinition[] {
  return SERVICES_CATALOG.filter((s) => s.category === category)
}
